environment: dev

image:
  repository: rhianlopes/kafka-consumer
  tag: latest
  pullPolicy: Always

network:
  port: 3000

env:
  KAFKA_BROKERS: 'kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092'
  KAFKA_CONSUMER_GROUP: 'example-consumer-group'
  KAFKA_TOPIC: 'example-topic'
  KAFKA_USER: 'user1'
  KAFKA_PASSWORD: '<client_password>'

scaling: 
  enabled: false
  minReplicas: 0
  maxReplicas: 4
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: 172.20.0.4:9092
      consumerGroup: example-consumer-group
      topic: example-topic
      lagThreshold: "5"
      offsetResetPolicy: earliest
