{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.environment }}-{{ .Release.Name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Release.Name }}
  pollingInterval: {{ .Values.scaling.pollingInterval }}
  cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.scaling.minReplicas }}
  maxReplicaCount: {{ .Values.scaling.maxReplicas }}
  {{- if .Values.scaling.triggers }}
  triggers: 
    {{- toYaml .Values.scaling.triggers | nindent 2 }}
  {{- end }}
{{- end }}
